import arcade

# GAME CONSTANTS
SCREEN_HEIGHT = 600
SCREEN_WIDTH = 800
CENTER_X = SCREEN_WIDTH / 2
CENTER_Y = SCREEN_HEIGHT / 2
GRAVITY = 0.5
MAZE_WIDTH = 30
MAZE_HEIGHT = 30
MOVE_SPEED = 3
RIGHT = "r"
LEFT = "l"
UP = "u"
DOWN = "d"
SCALE = 0.2

# ANIMAL CONSTANTS
PLAYER_JUMP_SPEED = 15
PLAYER_ANIMATION_RATE = 3
PLAYER_PATH = ":resources:images/enemies/slimeBlock.png"
PLAYER_FALLING = arcade.load_texture(f"{PLAYER_PATH}")
PLAYER_IDLE = arcade.load_texture(f"{PLAYER_PATH}")
PLAYER_JUMPING = arcade.load_texture(f"{PLAYER_PATH}")


# GROUND CONSTANTS
